steps:

- name: 'gcr.io/cloud-builders/docker'
  id: Cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
     docker pull gcr.io/$PROJECT_ID/cloud-run-test:$BRANCH_NAME || exit 0
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-run-test:$BRANCH_NAME', '--cache-from', 'gcr.io/$PROJECT_ID/cloud-run-test:$BRANCH_NAME', '.']
  waitFor: ['Cache']

# Push new image to repository
- name: 'gcr.io/cloud-builders/docker'
  id: Pushed
  args: ['push', 'gcr.io/$PROJECT_ID/cloud-run-test:$BRANCH_NAME']
  waitFor: ['Build']

# release cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    'cloud-run-test-$BRANCH_NAME',
    '--image', 'gcr.io/$PROJECT_ID/cloud-run-test:$BRANCH_NAME',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--memory', '1Gi',
    '--max-instances', '1',
    '--ingress', 'all',
    '--set-env-vars', 'BRANCH_NAME=$BRANCH_NAME'
  ]

options:
  volumes:
    - name: 'shared'
      path: '/shared'

images:
- 'gcr.io/$PROJECT_ID/cloud-run-test:$BRANCH_NAME'
