name: Jira Ticket Checker

on:
  pull_request:
    branches: [ master ]
    types: [ opened, edited, reopened ]

env:
  ATLASSIAN_URL: https://woolworths-agile.atlassian.net

jobs:
  action:
    if: ${{ github.head_ref != 'prod' && github.base_ref == 'master'}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Jira Ticket Checker
        uses: ./.github/actions/jira-ticket-checker
        id: jira-check
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          atlassianToken: ${{secrets.JIRA_AUTH_TOKEN}}
          prTitle: ${{github.event.pull_request.title}}
          prHtmlUrl: ${{github.event.pull_request.html_url}}
          atlassianInstance: ${{env.ATLASSIAN_URL}}
